/**
 * generated by Xtext 2.19.0
 */
package prettyCompilation.wh;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link prettyCompilation.wh.Expr#getValeur <em>Valeur</em>}</li>
 *   <li>{@link prettyCompilation.wh.Expr#getSymb <em>Symb</em>}</li>
 *   <li>{@link prettyCompilation.wh.Expr#getOpe <em>Ope</em>}</li>
 *   <li>{@link prettyCompilation.wh.Expr#getLexpr <em>Lexpr</em>}</li>
 *   <li>{@link prettyCompilation.wh.Expr#getExpr <em>Expr</em>}</li>
 *   <li>{@link prettyCompilation.wh.Expr#getEx1 <em>Ex1</em>}</li>
 *   <li>{@link prettyCompilation.wh.Expr#getEx2 <em>Ex2</em>}</li>
 * </ul>
 *
 * @see prettyCompilation.wh.WhPackage#getExpr()
 * @model
 * @generated
 */
public interface Expr extends EObject
{
  /**
   * Returns the value of the '<em><b>Valeur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valeur</em>' attribute.
   * @see #setValeur(String)
   * @see prettyCompilation.wh.WhPackage#getExpr_Valeur()
   * @model
   * @generated
   */
  String getValeur();

  /**
   * Sets the value of the '{@link prettyCompilation.wh.Expr#getValeur <em>Valeur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valeur</em>' attribute.
   * @see #getValeur()
   * @generated
   */
  void setValeur(String value);

  /**
   * Returns the value of the '<em><b>Symb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Symb</em>' attribute.
   * @see #setSymb(String)
   * @see prettyCompilation.wh.WhPackage#getExpr_Symb()
   * @model
   * @generated
   */
  String getSymb();

  /**
   * Sets the value of the '{@link prettyCompilation.wh.Expr#getSymb <em>Symb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Symb</em>' attribute.
   * @see #getSymb()
   * @generated
   */
  void setSymb(String value);

  /**
   * Returns the value of the '<em><b>Ope</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ope</em>' attribute.
   * @see #setOpe(String)
   * @see prettyCompilation.wh.WhPackage#getExpr_Ope()
   * @model
   * @generated
   */
  String getOpe();

  /**
   * Sets the value of the '{@link prettyCompilation.wh.Expr#getOpe <em>Ope</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ope</em>' attribute.
   * @see #getOpe()
   * @generated
   */
  void setOpe(String value);

  /**
   * Returns the value of the '<em><b>Lexpr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lexpr</em>' containment reference.
   * @see #setLexpr(Lexpr)
   * @see prettyCompilation.wh.WhPackage#getExpr_Lexpr()
   * @model containment="true"
   * @generated
   */
  Lexpr getLexpr();

  /**
   * Sets the value of the '{@link prettyCompilation.wh.Expr#getLexpr <em>Lexpr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lexpr</em>' containment reference.
   * @see #getLexpr()
   * @generated
   */
  void setLexpr(Lexpr value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expr)
   * @see prettyCompilation.wh.WhPackage#getExpr_Expr()
   * @model containment="true"
   * @generated
   */
  Expr getExpr();

  /**
   * Sets the value of the '{@link prettyCompilation.wh.Expr#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expr value);

  /**
   * Returns the value of the '<em><b>Ex1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ex1</em>' containment reference.
   * @see #setEx1(Expr)
   * @see prettyCompilation.wh.WhPackage#getExpr_Ex1()
   * @model containment="true"
   * @generated
   */
  Expr getEx1();

  /**
   * Sets the value of the '{@link prettyCompilation.wh.Expr#getEx1 <em>Ex1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ex1</em>' containment reference.
   * @see #getEx1()
   * @generated
   */
  void setEx1(Expr value);

  /**
   * Returns the value of the '<em><b>Ex2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ex2</em>' containment reference.
   * @see #setEx2(Expr)
   * @see prettyCompilation.wh.WhPackage#getExpr_Ex2()
   * @model containment="true"
   * @generated
   */
  Expr getEx2();

  /**
   * Sets the value of the '{@link prettyCompilation.wh.Expr#getEx2 <em>Ex2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ex2</em>' containment reference.
   * @see #getEx2()
   * @generated
   */
  void setEx2(Expr value);

} // Expr
