/**
 * generated by Xtext 2.19.0
 */
package prettyCompilation.wh;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Write</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link prettyCompilation.wh.Write#getVariable <em>Variable</em>}</li>
 * </ul>
 *
 * @see prettyCompilation.wh.WhPackage#getWrite()
 * @model
 * @generated
 */
public interface Write extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' attribute list.
   * @see prettyCompilation.wh.WhPackage#getWrite_Variable()
   * @model unique="false"
   * @generated
   */
  EList<String> getVariable();

} // Write
