/**
 * generated by Xtext 2.19.0
 */
package pretty.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import pretty.WhRuntimeModule;
import pretty.WhStandaloneSetup;
import pretty.ide.WhIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class WhIdeSetup extends WhStandaloneSetup {
  @Override
  public Injector createInjector() {
    WhRuntimeModule _whRuntimeModule = new WhRuntimeModule();
    WhIdeModule _whIdeModule = new WhIdeModule();
    return Guice.createInjector(Modules2.mixin(_whRuntimeModule, _whIdeModule));
  }
}
