/**
 * generated by Xtext 2.19.0
 */
package pretty.ide;

import pretty.ide.AbstractWhIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class WhIdeModule extends AbstractWhIdeModule {
}
