/**
 * generated by Xtext 2.19.0
 */
package prettyCompilation;

import prettyCompilation.AbstractWhRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class WhRuntimeModule extends AbstractWhRuntimeModule {
}
