/**
 * generated by Xtext 2.19.0
 */
package prettyCompilation;

import prettyCompilation.WhStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class WhStandaloneSetup extends WhStandaloneSetupGenerated {
  public static void doSetup() {
    new WhStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
