/**
 * generated by Xtext 2.19.0
 */
package pretty.wh.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import pretty.wh.Affectation;
import pretty.wh.Expr;
import pretty.wh.WhPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Affectation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link pretty.wh.impl.AffectationImpl#getAffectations <em>Affectations</em>}</li>
 *   <li>{@link pretty.wh.impl.AffectationImpl#getValeurs <em>Valeurs</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AffectationImpl extends MinimalEObjectImpl.Container implements Affectation
{
  /**
   * The cached value of the '{@link #getAffectations() <em>Affectations</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAffectations()
   * @generated
   * @ordered
   */
  protected EList<String> affectations;

  /**
   * The cached value of the '{@link #getValeurs() <em>Valeurs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValeurs()
   * @generated
   * @ordered
   */
  protected EList<Expr> valeurs;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AffectationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WhPackage.Literals.AFFECTATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getAffectations()
  {
    if (affectations == null)
    {
      affectations = new EDataTypeEList<String>(String.class, this, WhPackage.AFFECTATION__AFFECTATIONS);
    }
    return affectations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Expr> getValeurs()
  {
    if (valeurs == null)
    {
      valeurs = new EObjectContainmentEList<Expr>(Expr.class, this, WhPackage.AFFECTATION__VALEURS);
    }
    return valeurs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WhPackage.AFFECTATION__VALEURS:
        return ((InternalEList<?>)getValeurs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WhPackage.AFFECTATION__AFFECTATIONS:
        return getAffectations();
      case WhPackage.AFFECTATION__VALEURS:
        return getValeurs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WhPackage.AFFECTATION__AFFECTATIONS:
        getAffectations().clear();
        getAffectations().addAll((Collection<? extends String>)newValue);
        return;
      case WhPackage.AFFECTATION__VALEURS:
        getValeurs().clear();
        getValeurs().addAll((Collection<? extends Expr>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WhPackage.AFFECTATION__AFFECTATIONS:
        getAffectations().clear();
        return;
      case WhPackage.AFFECTATION__VALEURS:
        getValeurs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WhPackage.AFFECTATION__AFFECTATIONS:
        return affectations != null && !affectations.isEmpty();
      case WhPackage.AFFECTATION__VALEURS:
        return valeurs != null && !valeurs.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (affectations: ");
    result.append(affectations);
    result.append(')');
    return result.toString();
  }

} //AffectationImpl
