/**
 * generated by Xtext 2.19.0
 */
package pretty.wh;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Affectation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pretty.wh.Affectation#getAffectations <em>Affectations</em>}</li>
 *   <li>{@link pretty.wh.Affectation#getValeurs <em>Valeurs</em>}</li>
 * </ul>
 *
 * @see pretty.wh.WhPackage#getAffectation()
 * @model
 * @generated
 */
public interface Affectation extends EObject
{
  /**
   * Returns the value of the '<em><b>Affectations</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Affectations</em>' attribute list.
   * @see pretty.wh.WhPackage#getAffectation_Affectations()
   * @model unique="false"
   * @generated
   */
  EList<String> getAffectations();

  /**
   * Returns the value of the '<em><b>Valeurs</b></em>' containment reference list.
   * The list contents are of type {@link pretty.wh.Expr}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valeurs</em>' containment reference list.
   * @see pretty.wh.WhPackage#getAffectation_Valeurs()
   * @model containment="true"
   * @generated
   */
  EList<Expr> getValeurs();

} // Affectation
