/**
 * generated by Xtext 2.19.0
 */
package pretty.wh;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pretty.wh.Definition#getRead <em>Read</em>}</li>
 *   <li>{@link pretty.wh.Definition#getCommands <em>Commands</em>}</li>
 *   <li>{@link pretty.wh.Definition#getWrite <em>Write</em>}</li>
 * </ul>
 *
 * @see pretty.wh.WhPackage#getDefinition()
 * @model
 * @generated
 */
public interface Definition extends EObject
{
  /**
   * Returns the value of the '<em><b>Read</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Read</em>' containment reference.
   * @see #setRead(Read)
   * @see pretty.wh.WhPackage#getDefinition_Read()
   * @model containment="true"
   * @generated
   */
  Read getRead();

  /**
   * Sets the value of the '{@link pretty.wh.Definition#getRead <em>Read</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Read</em>' containment reference.
   * @see #getRead()
   * @generated
   */
  void setRead(Read value);

  /**
   * Returns the value of the '<em><b>Commands</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' containment reference.
   * @see #setCommands(Commands)
   * @see pretty.wh.WhPackage#getDefinition_Commands()
   * @model containment="true"
   * @generated
   */
  Commands getCommands();

  /**
   * Sets the value of the '{@link pretty.wh.Definition#getCommands <em>Commands</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Commands</em>' containment reference.
   * @see #getCommands()
   * @generated
   */
  void setCommands(Commands value);

  /**
   * Returns the value of the '<em><b>Write</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Write</em>' containment reference.
   * @see #setWrite(Write)
   * @see pretty.wh.WhPackage#getDefinition_Write()
   * @model containment="true"
   * @generated
   */
  Write getWrite();

  /**
   * Sets the value of the '{@link pretty.wh.Definition#getWrite <em>Write</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Write</em>' containment reference.
   * @see #getWrite()
   * @generated
   */
  void setWrite(Write value);

} // Definition
