/**
 * generated by Xtext 2.19.0
 */
package pretty.wh;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lexpr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pretty.wh.Lexpr#getExprs <em>Exprs</em>}</li>
 * </ul>
 *
 * @see pretty.wh.WhPackage#getLexpr()
 * @model
 * @generated
 */
public interface Lexpr extends EObject
{
  /**
   * Returns the value of the '<em><b>Exprs</b></em>' containment reference list.
   * The list contents are of type {@link pretty.wh.Expr}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exprs</em>' containment reference list.
   * @see pretty.wh.WhPackage#getLexpr_Exprs()
   * @model containment="true"
   * @generated
   */
  EList<Expr> getExprs();

} // Lexpr
