/*
 * generated by Xtext 2.19.0
 */
package prettyCompilation.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWhScopeProvider extends DelegatingScopeProvider {
}
