/**
 * generated by Xtext 2.19.0
 */
package pretty.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import pretty.ui.AbstractWhUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class WhUiModule extends AbstractWhUiModule {
  public WhUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
