/*
 * generated by Xtext 2.19.0
 */
package pretty.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import pretty.ui.internal.PrettyActivator;

public class WhUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PrettyActivator.getInstance().getInjector("pretty.Wh");
	}

}
