/*
 * generated by Xtext 2.19.0
 */
package pretty.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import pretty.WhRuntimeModule
import pretty.WhStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class WhIdeSetup extends WhStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new WhRuntimeModule, new WhIdeModule))
	}
	
}
