/*
 * generated by Xtext 2.19.0
 */
package prettyCompilation


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WhStandaloneSetup extends WhStandaloneSetupGenerated {

	def static void doSetup() {
		new WhStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
