/*
 * generated by Xtext 2.19.0
 */
package pretty.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import pretty.ui.internal.PrettyActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WhExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(PrettyActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		PrettyActivator activator = PrettyActivator.getInstance();
		return activator != null ? activator.getInjector(PrettyActivator.PRETTY_WH) : null;
	}

}
